### ISSUE TITLE
gm dapp epic

### ISSUE THREAD

**Issue by chadyj** [WalletConnect/gm-dapp#1]
# Overview

The gm dapp is used to dogfood the developer and user experience of web3inbox and push. 

There are 4 main components

- [x] Simple dapp. Users can connect, then opt-in to receive notifications (#2)
- [x] Backend notifier. A simple service that sends 'gm' messages to opted in users at 9am (#2)
- [x] Quick subscribe from within web3inbox (https://github.com/WalletConnect/gm-dapp/issues/5)
- [x] Sample wallet that receives PN's

The end result is that users can subscribe to the GM notifications, and receive these notifications as push notifications in our sample wallet, and within web3inbox.

By creating this, we can test the full flow and use this as a demo for pilot partners.

## Simple Dapp (#2)

First screen has a connect button.
After connecting, there is a "subscribe to gm" button

Users can also manage their subscription and unsubscribe.

## Backend notifier (#2)

A job that runs at 9am and sends a `gm` to Cast server for subscribed users

## Quick Subscribe from web3inbox

Add the GM app to the "explore app" section of web3inbox.
See spec https://github.com/WalletConnect/walletconnect-docs/pull/574

<img width="200" src="https://user-images.githubusercontent.com/116099/227501258-017e4bf8-6f0a-475e-b62f-7429aa6505ce.jpeg">

## Sample Wallet that receives notifications

Our sample wallet should receive PN's from GM

Not required, but ideally, tapping on the PN should open up web3inbox and deep link to the gm message.
